### ISSUE TITLE
JSX kullanışsız

### ISSUE THREAD

**Issue by cagatayikim** [formulanano/nanocar-builder-web#8]
Merhabalar. Projeye yakın zamanda react eklenmiş. Bu ileride iyi birşey olabilir. Fakat, script dosyalarının uzantıları .jsx olmamalı. Bu, anlaşılmayı zor hale getiriyor. Ayrıca hem şu anki, hem de yeni katılacak kişiler için bir zorlaştırıcı bir etken.
3 önemli .jsx uzantılı dosya var: MainMenu.jsx, ToolsMenu.jsx ve en önemlisi MainScene.jsx
Bu dosyalar src/components'in içinde. Bunların .js haline dönüştürülmesi, kuşkusuz projeye hız kazandırır ve verimini arttırır.
Ben nasıl dönüştürüleceğini bilmiyorum, ama kendi başına bu işi yapabilecek kişiler var aramızda.
Umarım bu işi halledebilirsiniz.
Kolay gelsin!

**Comment by drac** [comment]
@cagatayikim oncelikle yeni gelecek arkadaslar icin zorlastirici bir etken olmamasi icin projenin ana dili ingilizce olarak baslatildi ve bu sekilde devam etmesi daha yararli.

Secondly, there are literally **no performance** difference between `.jsx` and `.js` extensions. Your compiler will take care of extensions on build, you shouldn't worry about that.

**So you might ask that; which files should end with `.jsx`?**
Since JSX isn't standard JavaScript one could argue that anything that is not "plain" JavaScript should go into its own extensions ie., `.jsx` for JSX and `.ts` for TypeScript for example.

_find more about [here](https://stackoverflow.com/questions/46169472/reactjs-js-vs-jsx/46169636)_
